# vim: syntax=python:shiftwidth=4:tabstop=4:expandtab

def options(opt):
    pass
def configure(cnf):
    pass
def build(bld):
    bld(
        features='dart',
        source=bld.path.ant_glob('index.dart')
            + bld.path.ant_glob('**/*.html')
            + bld.path.ant_glob('**/*.css')
            + bld.path.ant_glob('**/*.js')
            + bld.path.ant_glob('**/*.yaml'),
        target='example'
    )

